LastBIOSFolder = ""
RecentROM = ["/home/leozin/Downloads/pokemon.nds"]
UITheme = ""
FastForwardFPS = 1000.0
AudioSync = false
TargetFPS = 60.0
PauseLostFocus = false
LimitFPS = true
SlowmoFPS = 30.0

[DS]
FirmwarePath = ""
BIOS7Path = ""
BIOS9Path = ""

[Audio]
Interpolation = 0
BitDepth = 0

[DLDI]
FolderPath = ""
FolderSync = false
ReadOnly = false
ImagePath = "dldi.bin"
ImageSize = 0
Enable = false

[DSi]
FullBIOSBoot = false
FirmwarePath = ""
BIOS9Path = ""
BIOS7Path = ""
NANDPath = ""

[DSi.DSP]
HLE = true

[DSi.SD]
FolderPath = ""
FolderSync = false
ReadOnly = false
ImagePath = "dsisd.bin"
ImageSize = 0
Enable = false

[DSi.Camera1]
DeviceName = ""
ImagePath = ""
InputType = 0
XFlip = false

[DSi.Camera0]
DeviceName = ""
ImagePath = ""
InputType = 0
XFlip = false

[Mouse]
HideSeconds = 5
Hide = false

[3D]
Renderer = 0

[3D.Soft]
Threaded = true

[Savestate]
RelocSRAM = false

[MP]
AudioMode = 1
RecvTimeout = 25

[LAN]
DirectMode = false

[Emu]
DirectBoot = true
ExternalBIOSEnable = false
ConsoleType = 0

[JIT]
Enable = false
FastMemory = true
BranchOptimisations = true
LiteralOptimisations = true
MaxBlockSize = 32

[Screen]
UseGL = false

[Mic]
WavPath = ""
Device = ""
InputType = 1

[Instance0]
EnableCheats = false
SaveFilePath = ""
JoystickID = 0
SavestatePath = ""
CheatFilePath = ""

[Instance0.RTC]
Offset = 0

[Instance0.DS]
[Instance0.DS.Battery]
LevelOkay = true

[Instance0.Keyboard]
HK_Reset = -1
HK_PowerButton = -1
HK_SwapScreenEmphasis = -1
HK_SwapScreens = -1
Left = 16777234
Y = 90
HK_FrameStep = -1
HK_SolarSensorIncrease = -1
A = 67
L = -1
R = -1
HK_GuitarGripRed = -1
HK_VolumeDown = -1
HK_GuitarGripBlue = -1
HK_Lid = -1
HK_SolarSensorDecrease = -1
HK_VolumeUp = -1
HK_GuitarGripGreen = -1
HK_SlowMoToggle = -1
HK_FastForwardToggle = -1
HK_GuitarGripYellow = -1
HK_FrameLimitToggle = -1
Up = 16777235
HK_FullscreenToggle = -1
HK_SlowMo = -1
HK_Pause = -1
Right = 16777236
Start = 86
Select = 66
X = 83
B = 88
Down = 16777237
HK_Mic = -1
HK_FastForward = -1

[Instance0.Window2]
Enabled = false

[Instance0.Joystick]
HK_Reset = -1
HK_PowerButton = -1
HK_SwapScreenEmphasis = -1
HK_SwapScreens = -1
Left = -1
Y = -1
HK_FrameStep = -1
HK_SolarSensorIncrease = -1
A = -1
L = -1
R = -1
HK_GuitarGripRed = -1
HK_VolumeDown = -1
HK_GuitarGripBlue = -1
HK_Lid = -1
HK_SolarSensorDecrease = -1
HK_VolumeUp = -1
HK_GuitarGripGreen = -1
HK_SlowMoToggle = -1
HK_FastForwardToggle = -1
HK_GuitarGripYellow = -1
HK_FrameLimitToggle = -1
Up = -1
HK_FullscreenToggle = -1
HK_SlowMo = -1
HK_Pause = -1
Right = -1
Start = -1
Select = -1
X = -1
B = -1
Down = -1
HK_Mic = -1
HK_FastForward = -1

[Instance0.Window0]
Enabled = true
ScreenFilter = false
ScreenAspectTop = 0
IntegerScaling = false
ScreenSizing = 0
ScreenSwap = false
ScreenGap = 0
ScreenAspectBot = 0
ScreenRotation = 0
ScreenLayout = 2
Geometry = "AdnQywADAAAAAAAAAAAAAAAABFoAAAG+AAAAAAAAAAD////+/////gAAAAACAAAABVYAAAAAAAAAAAAABFoAAAG+"
ShowOSD = true

[Instance0.Audio]
DSiVolumeSync = false
Volume = 256

[Instance0.Window3]
Enabled = false

[Instance0.Firmware]
MAC = ""
Message = ""
BirthdayDay = 1
BirthdayMonth = 1
FavouriteColour = 0
Language = 1
Username = "melonDS"

[Instance0.Window1]
Enabled = false

[Instance0.Gdb]
Enabled = false

[Instance0.Gdb.ARM9]
BreakOnStartup = false
Port = 3333

[Instance0.Gdb.ARM7]
BreakOnStartup = false
Port = 3334

